---
apiVersion: v1
kind: Secret
metadata:
  name: influxdb-auth
stringData:
  username: admin
  password: admin
---
apiVersion: v1
kind: Secret
metadata:
  name: influxdb-shared-secret
stringData:
  secret: MY RANDOM STRING
---