import React, {Component, MouseEvent} from 'react'

import Authorized, {EDITOR_ROLE} from 'src/auth/Authorized'

import DashboardsTable from 'src/dashboards/components/DashboardsTable'
import ImportDashboardOverlay from 'src/dashboards/components/ImportDashboardOverlay'
import SearchBar from 'src/hosts/components/SearchBar'
import FancyScrollbar from 'src/shared/components/FancyScrollbar'
import {ErrorHandling} from 'src/shared/decorators/errors'
import OverlayTechnology from 'src/reusable_ui/components/overlays/OverlayTechnology'
import Button from 'src/reusable_ui/components/button/Button'
import {ComponentColor, ComponentSize, ButtonShape} from 'src/reusable_ui/types'

import {Dashboard} from 'src/types'
import {Notification} from 'src/types/notifications'

interface Props {
  dashboards: Dashboard[]
  onDeleteDashboard: (dashboard: Dashboard) => () => void
  onCreateDashboard: () => void
  onCloneDashboard: (
    dashboard: Dashboard
  ) => (event: MouseEvent<HTMLButtonElement>) => void
  onExportDashboard: (dashboard: Dashboard) => () => void
  onImportDashboard: (dashboard: Dashboard) => void
  notify: (message: Notification) => void
  dashboardLink: string
}

interface State {
  searchTerm: string
  isOverlayVisible: boolean
}

@ErrorHandling
class DashboardsPageContents extends Component<Props, State> {
  constructor(props) {
    super(props)

    this.state = {
      searchTerm: '',
      isOverlayVisible: false,
    }
  }

  public render() {
    const {
      onDeleteDashboard,
      onCreateDashboard,
      onCloneDashboard,
      onExportDashboard,
      dashboardLink,
    } = this.props

    return (
      <FancyScrollbar className="page-contents">
        <div className="container-fluid">
          <div className="row">
            <div className="col-md-12">
              <div className="panel">
                {this.renderPanelHeading}
                <div className="panel-body">
                  <DashboardsTable
                    dashboards={this.filteredDashboards}
                    onDeleteDashboard={onDeleteDashboard}
                    onCreateDashboard={onCreateDashboard}
                    onCloneDashboard={onCloneDashboard}
                    onExportDashboard={onExportDashboard}
                    dashboardLink={dashboardLink}
                  />
                </div>
              </div>

              <div className="panel">
                <div className="panel-body">
                  <h3>Buttons</h3>
                  <table className="table">
                    <thead>
                      <tr>
                        <th />
                        <th>XS</th>
                        <th>SM</th>
                        <th>MD</th>
                        <th>LG</th>
                      </tr>
                    </thead>
                    <tbody>
                      <tr>
                        <td>Default</td>
                        <td>
                          <Button
                            color={ComponentColor.Default}
                            size={ComponentSize.ExtraSmall}
                            text="Example"
                          />
                          <Button
                            color={ComponentColor.Default}
                            size={ComponentSize.ExtraSmall}
                            text="Example"
                            disabled={true}
                          />
                        </td>
                        <td>
                          <Button
                            color={ComponentColor.Default}
                            size={ComponentSize.Small}
                            text="Example"
                          />
                          <Button
                            color={ComponentColor.Default}
                            size={ComponentSize.Small}
                            text="Example"
                            disabled={true}
                          />
                        </td>
                        <td>
                          <Button
                            color={ComponentColor.Default}
                            size={ComponentSize.Medium}
                            text="Example"
                          />
                          <Button
                            color={ComponentColor.Default}
                            size={ComponentSize.Medium}
                            text="Example"
                            disabled={true}
                          />
                        </td>
                        <td>
                          <Button
                            color={ComponentColor.Default}
                            size={ComponentSize.Large}
                            text="Example"
                          />
                          <Button
                            color={ComponentColor.Default}
                            size={ComponentSize.Large}
                            text="Example"
                            disabled={true}
                          />
                        </td>
                      </tr>
                      <tr>
                        <td>Primary</td>
                        <td>
                          <Button
                            color={ComponentColor.Primary}
                            size={ComponentSize.ExtraSmall}
                            text="Example"
                          />
                          <Button
                            color={ComponentColor.Primary}
                            size={ComponentSize.ExtraSmall}
                            text="Example"
                            disabled={true}
                          />
                        </td>
                        <td>
                          <Button
                            color={ComponentColor.Primary}
                            size={ComponentSize.Small}
                            text="Example"
                          />
                          <Button
                            color={ComponentColor.Primary}
                            size={ComponentSize.Small}
                            text="Example"
                            disabled={true}
                          />
                        </td>
                        <td>
                          <Button
                            color={ComponentColor.Primary}
                            size={ComponentSize.Medium}
                            text="Example"
                          />
                          <Button
                            color={ComponentColor.Primary}
                            size={ComponentSize.Medium}
                            text="Example"
                            disabled={true}
                          />
                        </td>
                        <td>
                          <Button
                            color={ComponentColor.Primary}
                            size={ComponentSize.Large}
                            text="Example"
                          />
                          <Button
                            color={ComponentColor.Primary}
                            size={ComponentSize.Large}
                            text="Example"
                            disabled={true}
                          />
                        </td>
                      </tr>
                      <tr>
                        <td>Secondary</td>
                        <td>
                          <Button
                            color={ComponentColor.Secondary}
                            size={ComponentSize.ExtraSmall}
                            text="Example"
                          />
                          <Button
                            color={ComponentColor.Secondary}
                            size={ComponentSize.ExtraSmall}
                            text="Example"
                            disabled={true}
                          />
                        </td>
                        <td>
                          <Button
                            color={ComponentColor.Secondary}
                            size={ComponentSize.Small}
                            text="Example"
                          />
                          <Button
                            color={ComponentColor.Secondary}
                            size={ComponentSize.Small}
                            text="Example"
                            disabled={true}
                          />
                        </td>
                        <td>
                          <Button
                            color={ComponentColor.Secondary}
                            size={ComponentSize.Medium}
                            text="Example"
                          />
                          <Button
                            color={ComponentColor.Secondary}
                            size={ComponentSize.Medium}
                            text="Example"
                            disabled={true}
                          />
                        </td>
                        <td>
                          <Button
                            color={ComponentColor.Secondary}
                            size={ComponentSize.Large}
                            text="Example"
                          />
                          <Button
                            color={ComponentColor.Secondary}
                            size={ComponentSize.Large}
                            text="Example"
                            disabled={true}
                          />
                        </td>
                      </tr>
                      <tr>
                        <td>Success</td>
                        <td>
                          <Button
                            color={ComponentColor.Success}
                            size={ComponentSize.ExtraSmall}
                            text="Example"
                          />
                          <Button
                            color={ComponentColor.Success}
                            size={ComponentSize.ExtraSmall}
                            text="Example"
                            disabled={true}
                          />
                        </td>
                        <td>
                          <Button
                            color={ComponentColor.Success}
                            size={ComponentSize.Small}
                            text="Example"
                          />
                          <Button
                            color={ComponentColor.Success}
                            size={ComponentSize.Small}
                            text="Example"
                            disabled={true}
                          />
                        </td>
                        <td>
                          <Button
                            color={ComponentColor.Success}
                            size={ComponentSize.Medium}
                            text="Example"
                          />
                          <Button
                            color={ComponentColor.Success}
                            size={ComponentSize.Medium}
                            text="Example"
                            disabled={true}
                          />
                        </td>
                        <td>
                          <Button
                            color={ComponentColor.Success}
                            size={ComponentSize.Large}
                            text="Example"
                          />
                          <Button
                            color={ComponentColor.Success}
                            size={ComponentSize.Large}
                            text="Example"
                            disabled={true}
                          />
                        </td>
                      </tr>
                      <tr>
                        <td>Warning</td>
                        <td>
                          <Button
                            color={ComponentColor.Warning}
                            size={ComponentSize.ExtraSmall}
                            text="Example"
                          />
                          <Button
                            color={ComponentColor.Warning}
                            size={ComponentSize.ExtraSmall}
                            text="Example"
                            disabled={true}
                          />
                        </td>
                        <td>
                          <Button
                            color={ComponentColor.Warning}
                            size={ComponentSize.Small}
                            text="Example"
                          />
                          <Button
                            color={ComponentColor.Warning}
                            size={ComponentSize.Small}
                            text="Example"
                            disabled={true}
                          />
                        </td>
                        <td>
                          <Button
                            color={ComponentColor.Warning}
                            size={ComponentSize.Medium}
                            text="Example"
                          />
                          <Button
                            color={ComponentColor.Warning}
                            size={ComponentSize.Medium}
                            text="Example"
                            disabled={true}
                          />
                        </td>
                        <td>
                          <Button
                            color={ComponentColor.Warning}
                            size={ComponentSize.Large}
                            text="Example"
                          />
                          <Button
                            color={ComponentColor.Warning}
                            size={ComponentSize.Large}
                            text="Example"
                            disabled={true}
                          />
                        </td>
                      </tr>
                      <tr>
                        <td>Danger</td>
                        <td>
                          <Button
                            color={ComponentColor.Danger}
                            size={ComponentSize.ExtraSmall}
                            text="Example"
                          />
                          <Button
                            color={ComponentColor.Danger}
                            size={ComponentSize.ExtraSmall}
                            text="Example"
                            disabled={true}
                          />
                        </td>
                        <td>
                          <Button
                            color={ComponentColor.Danger}
                            size={ComponentSize.Small}
                            text="Example"
                          />
                          <Button
                            color={ComponentColor.Danger}
                            size={ComponentSize.Small}
                            text="Example"
                            disabled={true}
                          />
                        </td>
                        <td>
                          <Button
                            color={ComponentColor.Danger}
                            size={ComponentSize.Medium}
                            text="Example"
                          />
                          <Button
                            color={ComponentColor.Danger}
                            size={ComponentSize.Medium}
                            text="Example"
                            disabled={true}
                          />
                        </td>
                        <td>
                          <Button
                            color={ComponentColor.Danger}
                            size={ComponentSize.Large}
                            text="Example"
                          />
                          <Button
                            color={ComponentColor.Danger}
                            size={ComponentSize.Large}
                            text="Example"
                            disabled={true}
                          />
                        </td>
                      </tr>
                    </tbody>
                  </table>
                </div>
              </div>

              <div className="panel">
                <div className="panel-body">
                  <h3>Icon Buttons</h3>
                  <table className="table">
                    <thead>
                      <tr>
                        <th />
                        <th>XS</th>
                        <th>SM</th>
                        <th>MD</th>
                        <th>LG</th>
                      </tr>
                    </thead>
                    <tbody>
                      <tr>
                        <td>Default</td>
                        <td>
                          <Button
                            color={ComponentColor.Default}
                            size={ComponentSize.ExtraSmall}
                            text="Example"
                            icon="oauth"
                          />
                          <Button
                            color={ComponentColor.Default}
                            size={ComponentSize.ExtraSmall}
                            text="Example"
                            icon="oauth"
                            disabled={true}
                          />
                        </td>
                        <td>
                          <Button
                            color={ComponentColor.Default}
                            size={ComponentSize.Small}
                            text="Example"
                            icon="oauth"
                          />
                          <Button
                            color={ComponentColor.Default}
                            size={ComponentSize.Small}
                            text="Example"
                            icon="oauth"
                            disabled={true}
                          />
                        </td>
                        <td>
                          <Button
                            color={ComponentColor.Default}
                            size={ComponentSize.Medium}
                            text="Example"
                            icon="oauth"
                          />
                          <Button
                            color={ComponentColor.Default}
                            size={ComponentSize.Medium}
                            text="Example"
                            icon="oauth"
                            disabled={true}
                          />
                        </td>
                        <td>
                          <Button
                            color={ComponentColor.Default}
                            size={ComponentSize.Large}
                            text="Example"
                            icon="oauth"
                          />
                          <Button
                            color={ComponentColor.Default}
                            size={ComponentSize.Large}
                            text="Example"
                            icon="oauth"
                            disabled={true}
                          />
                        </td>
                      </tr>
                      <tr>
                        <td>Primary</td>
                        <td>
                          <Button
                            color={ComponentColor.Primary}
                            size={ComponentSize.ExtraSmall}
                            text="Example"
                            icon="oauth"
                          />
                          <Button
                            color={ComponentColor.Primary}
                            size={ComponentSize.ExtraSmall}
                            text="Example"
                            icon="oauth"
                            disabled={true}
                          />
                        </td>
                        <td>
                          <Button
                            color={ComponentColor.Primary}
                            size={ComponentSize.Small}
                            text="Example"
                            icon="oauth"
                          />
                          <Button
                            color={ComponentColor.Primary}
                            size={ComponentSize.Small}
                            text="Example"
                            icon="oauth"
                            disabled={true}
                          />
                        </td>
                        <td>
                          <Button
                            color={ComponentColor.Primary}
                            size={ComponentSize.Medium}
                            text="Example"
                            icon="oauth"
                          />
                          <Button
                            color={ComponentColor.Primary}
                            size={ComponentSize.Medium}
                            text="Example"
                            icon="oauth"
                            disabled={true}
                          />
                        </td>
                        <td>
                          <Button
                            color={ComponentColor.Primary}
                            size={ComponentSize.Large}
                            text="Example"
                            icon="oauth"
                          />
                          <Button
                            color={ComponentColor.Primary}
                            size={ComponentSize.Large}
                            text="Example"
                            icon="oauth"
                            disabled={true}
                          />
                        </td>
                      </tr>
                      <tr>
                        <td>Secondary</td>
                        <td>
                          <Button
                            color={ComponentColor.Secondary}
                            size={ComponentSize.ExtraSmall}
                            text="Example"
                            icon="oauth"
                          />
                          <Button
                            color={ComponentColor.Secondary}
                            size={ComponentSize.ExtraSmall}
                            text="Example"
                            icon="oauth"
                            disabled={true}
                          />
                        </td>
                        <td>
                          <Button
                            color={ComponentColor.Secondary}
                            size={ComponentSize.Small}
                            text="Example"
                            icon="oauth"
                          />
                          <Button
                            color={ComponentColor.Secondary}
                            size={ComponentSize.Small}
                            text="Example"
                            icon="oauth"
                            disabled={true}
                          />
                        </td>
                        <td>
                          <Button
                            color={ComponentColor.Secondary}
                            size={ComponentSize.Medium}
                            text="Example"
                            icon="oauth"
                          />
                          <Button
                            color={ComponentColor.Secondary}
                            size={ComponentSize.Medium}
                            text="Example"
                            icon="oauth"
                            disabled={true}
                          />
                        </td>
                        <td>
                          <Button
                            color={ComponentColor.Secondary}
                            size={ComponentSize.Large}
                            text="Example"
                            icon="oauth"
                          />
                          <Button
                            color={ComponentColor.Secondary}
                            size={ComponentSize.Large}
                            text="Example"
                            icon="oauth"
                            disabled={true}
                          />
                        </td>
                      </tr>
                      <tr>
                        <td>Success</td>
                        <td>
                          <Button
                            color={ComponentColor.Success}
                            size={ComponentSize.ExtraSmall}
                            text="Example"
                            icon="oauth"
                          />
                          <Button
                            color={ComponentColor.Success}
                            size={ComponentSize.ExtraSmall}
                            text="Example"
                            icon="oauth"
                            disabled={true}
                          />
                        </td>
                        <td>
                          <Button
                            color={ComponentColor.Success}
                            size={ComponentSize.Small}
                            text="Example"
                            icon="oauth"
                          />
                          <Button
                            color={ComponentColor.Success}
                            size={ComponentSize.Small}
                            text="Example"
                            icon="oauth"
                            disabled={true}
                          />
                        </td>
                        <td>
                          <Button
                            color={ComponentColor.Success}
                            size={ComponentSize.Medium}
                            text="Example"
                            icon="oauth"
                          />
                          <Button
                            color={ComponentColor.Success}
                            size={ComponentSize.Medium}
                            text="Example"
                            icon="oauth"
                            disabled={true}
                          />
                        </td>
                        <td>
                          <Button
                            color={ComponentColor.Success}
                            size={ComponentSize.Large}
                            text="Example"
                            icon="oauth"
                          />
                          <Button
                            color={ComponentColor.Success}
                            size={ComponentSize.Large}
                            text="Example"
                            icon="oauth"
                            disabled={true}
                          />
                        </td>
                      </tr>
                      <tr>
                        <td>Warning</td>
                        <td>
                          <Button
                            color={ComponentColor.Warning}
                            size={ComponentSize.ExtraSmall}
                            text="Example"
                            icon="oauth"
                          />
                          <Button
                            color={ComponentColor.Warning}
                            size={ComponentSize.ExtraSmall}
                            text="Example"
                            icon="oauth"
                            disabled={true}
                          />
                        </td>
                        <td>
                          <Button
                            color={ComponentColor.Warning}
                            size={ComponentSize.Small}
                            text="Example"
                            icon="oauth"
                          />
                          <Button
                            color={ComponentColor.Warning}
                            size={ComponentSize.Small}
                            text="Example"
                            icon="oauth"
                            disabled={true}
                          />
                        </td>
                        <td>
                          <Button
                            color={ComponentColor.Warning}
                            size={ComponentSize.Medium}
                            text="Example"
                            icon="oauth"
                          />
                          <Button
                            color={ComponentColor.Warning}
                            size={ComponentSize.Medium}
                            text="Example"
                            icon="oauth"
                            disabled={true}
                          />
                        </td>
                        <td>
                          <Button
                            color={ComponentColor.Warning}
                            size={ComponentSize.Large}
                            text="Example"
                            icon="oauth"
                          />
                          <Button
                            color={ComponentColor.Warning}
                            size={ComponentSize.Large}
                            text="Example"
                            icon="oauth"
                            disabled={true}
                          />
                        </td>
                      </tr>
                      <tr>
                        <td>Danger</td>
                        <td>
                          <Button
                            color={ComponentColor.Danger}
                            size={ComponentSize.ExtraSmall}
                            text="Example"
                            icon="oauth"
                          />
                          <Button
                            color={ComponentColor.Danger}
                            size={ComponentSize.ExtraSmall}
                            text="Example"
                            icon="oauth"
                            disabled={true}
                          />
                        </td>
                        <td>
                          <Button
                            color={ComponentColor.Danger}
                            size={ComponentSize.Small}
                            text="Example"
                            icon="oauth"
                          />
                          <Button
                            color={ComponentColor.Danger}
                            size={ComponentSize.Small}
                            text="Example"
                            icon="oauth"
                            disabled={true}
                          />
                        </td>
                        <td>
                          <Button
                            color={ComponentColor.Danger}
                            size={ComponentSize.Medium}
                            text="Example"
                            icon="oauth"
                          />
                          <Button
                            color={ComponentColor.Danger}
                            size={ComponentSize.Medium}
                            text="Example"
                            icon="oauth"
                            disabled={true}
                          />
                        </td>
                        <td>
                          <Button
                            color={ComponentColor.Danger}
                            size={ComponentSize.Large}
                            text="Example"
                            icon="oauth"
                          />
                          <Button
                            color={ComponentColor.Danger}
                            size={ComponentSize.Large}
                            text="Example"
                            icon="oauth"
                            disabled={true}
                          />
                        </td>
                      </tr>
                    </tbody>
                  </table>
                </div>
              </div>

              <div className="panel">
                <div className="panel-body">
                  <h3>Square Buttons</h3>
                  <table className="table">
                    <thead>
                      <tr>
                        <th />
                        <th>XS</th>
                        <th>SM</th>
                        <th>MD</th>
                        <th>LG</th>
                      </tr>
                    </thead>
                    <tbody>
                      <tr>
                        <td>Default</td>
                        <td>
                          <Button
                            color={ComponentColor.Default}
                            size={ComponentSize.ExtraSmall}
                            shape={ButtonShape.Square}
                            text="Example"
                            icon="oauth"
                          />
                          <Button
                            color={ComponentColor.Default}
                            size={ComponentSize.ExtraSmall}
                            shape={ButtonShape.Square}
                            text="Example"
                            icon="oauth"
                            disabled={true}
                          />
                        </td>
                        <td>
                          <Button
                            color={ComponentColor.Default}
                            size={ComponentSize.Small}
                            shape={ButtonShape.Square}
                            text="Example"
                            icon="oauth"
                          />
                          <Button
                            color={ComponentColor.Default}
                            size={ComponentSize.Small}
                            shape={ButtonShape.Square}
                            text="Example"
                            icon="oauth"
                            disabled={true}
                          />
                        </td>
                        <td>
                          <Button
                            color={ComponentColor.Default}
                            size={ComponentSize.Medium}
                            shape={ButtonShape.Square}
                            text="Example"
                            icon="oauth"
                          />
                          <Button
                            color={ComponentColor.Default}
                            size={ComponentSize.Medium}
                            shape={ButtonShape.Square}
                            text="Example"
                            icon="oauth"
                            disabled={true}
                          />
                        </td>
                        <td>
                          <Button
                            color={ComponentColor.Default}
                            size={ComponentSize.Large}
                            shape={ButtonShape.Square}
                            text="Example"
                            icon="oauth"
                          />
                          <Button
                            color={ComponentColor.Default}
                            size={ComponentSize.Large}
                            shape={ButtonShape.Square}
                            text="Example"
                            icon="oauth"
                            disabled={true}
                          />
                        </td>
                      </tr>
                      <tr>
                        <td>Primary</td>
                        <td>
                          <Button
                            color={ComponentColor.Primary}
                            size={ComponentSize.ExtraSmall}
                            shape={ButtonShape.Square}
                            text="Example"
                            icon="oauth"
                          />
                          <Button
                            color={ComponentColor.Primary}
                            size={ComponentSize.ExtraSmall}
                            shape={ButtonShape.Square}
                            text="Example"
                            icon="oauth"
                            disabled={true}
                          />
                        </td>
                        <td>
                          <Button
                            color={ComponentColor.Primary}
                            size={ComponentSize.Small}
                            shape={ButtonShape.Square}
                            text="Example"
                            icon="oauth"
                          />
                          <Button
                            color={ComponentColor.Primary}
                            size={ComponentSize.Small}
                            shape={ButtonShape.Square}
                            text="Example"
                            icon="oauth"
                            disabled={true}
                          />
                        </td>
                        <td>
                          <Button
                            color={ComponentColor.Primary}
                            size={ComponentSize.Medium}
                            shape={ButtonShape.Square}
                            text="Example"
                            icon="oauth"
                          />
                          <Button
                            color={ComponentColor.Primary}
                            size={ComponentSize.Medium}
                            shape={ButtonShape.Square}
                            text="Example"
                            icon="oauth"
                            disabled={true}
                          />
                        </td>
                        <td>
                          <Button
                            color={ComponentColor.Primary}
                            size={ComponentSize.Large}
                            shape={ButtonShape.Square}
                            text="Example"
                            icon="oauth"
                          />
                          <Button
                            color={ComponentColor.Primary}
                            size={ComponentSize.Large}
                            shape={ButtonShape.Square}
                            text="Example"
                            icon="oauth"
                            disabled={true}
                          />
                        </td>
                      </tr>
                      <tr>
                        <td>Secondary</td>
                        <td>
                          <Button
                            color={ComponentColor.Secondary}
                            size={ComponentSize.ExtraSmall}
                            shape={ButtonShape.Square}
                            text="Example"
                            icon="oauth"
                          />
                          <Button
                            color={ComponentColor.Secondary}
                            size={ComponentSize.ExtraSmall}
                            shape={ButtonShape.Square}
                            text="Example"
                            icon="oauth"
                            disabled={true}
                          />
                        </td>
                        <td>
                          <Button
                            color={ComponentColor.Secondary}
                            size={ComponentSize.Small}
                            shape={ButtonShape.Square}
                            text="Example"
                            icon="oauth"
                          />
                          <Button
                            color={ComponentColor.Secondary}
                            size={ComponentSize.Small}
                            shape={ButtonShape.Square}
                            text="Example"
                            icon="oauth"
                            disabled={true}
                          />
                        </td>
                        <td>
                          <Button
                            color={ComponentColor.Secondary}
                            size={ComponentSize.Medium}
                            shape={ButtonShape.Square}
                            text="Example"
                            icon="oauth"
                          />
                          <Button
                            color={ComponentColor.Secondary}
                            size={ComponentSize.Medium}
                            shape={ButtonShape.Square}
                            text="Example"
                            icon="oauth"
                            disabled={true}
                          />
                        </td>
                        <td>
                          <Button
                            color={ComponentColor.Secondary}
                            size={ComponentSize.Large}
                            shape={ButtonShape.Square}
                            text="Example"
                            icon="oauth"
                          />
                          <Button
                            color={ComponentColor.Secondary}
                            size={ComponentSize.Large}
                            shape={ButtonShape.Square}
                            text="Example"
                            icon="oauth"
                            disabled={true}
                          />
                        </td>
                      </tr>
                      <tr>
                        <td>Success</td>
                        <td>
                          <Button
                            color={ComponentColor.Success}
                            size={ComponentSize.ExtraSmall}
                            shape={ButtonShape.Square}
                            text="Example"
                            icon="oauth"
                          />
                          <Button
                            color={ComponentColor.Success}
                            size={ComponentSize.ExtraSmall}
                            shape={ButtonShape.Square}
                            text="Example"
                            icon="oauth"
                            disabled={true}
                          />
                        </td>
                        <td>
                          <Button
                            color={ComponentColor.Success}
                            size={ComponentSize.Small}
                            shape={ButtonShape.Square}
                            text="Example"
                            icon="oauth"
                          />
                          <Button
                            color={ComponentColor.Success}
                            size={ComponentSize.Small}
                            shape={ButtonShape.Square}
                            text="Example"
                            icon="oauth"
                            disabled={true}
                          />
                        </td>
                        <td>
                          <Button
                            color={ComponentColor.Success}
                            size={ComponentSize.Medium}
                            shape={ButtonShape.Square}
                            text="Example"
                            icon="oauth"
                          />
                          <Button
                            color={ComponentColor.Success}
                            size={ComponentSize.Medium}
                            shape={ButtonShape.Square}
                            text="Example"
                            icon="oauth"
                            disabled={true}
                          />
                        </td>
                        <td>
                          <Button
                            color={ComponentColor.Success}
                            size={ComponentSize.Large}
                            shape={ButtonShape.Square}
                            text="Example"
                            icon="oauth"
                          />
                          <Button
                            color={ComponentColor.Success}
                            size={ComponentSize.Large}
                            shape={ButtonShape.Square}
                            text="Example"
                            icon="oauth"
                            disabled={true}
                          />
                        </td>
                      </tr>
                      <tr>
                        <td>Warning</td>
                        <td>
                          <Button
                            color={ComponentColor.Warning}
                            size={ComponentSize.ExtraSmall}
                            shape={ButtonShape.Square}
                            text="Example"
                            icon="oauth"
                          />
                          <Button
                            color={ComponentColor.Warning}
                            size={ComponentSize.ExtraSmall}
                            shape={ButtonShape.Square}
                            text="Example"
                            icon="oauth"
                            disabled={true}
                          />
                        </td>
                        <td>
                          <Button
                            color={ComponentColor.Warning}
                            size={ComponentSize.Small}
                            shape={ButtonShape.Square}
                            text="Example"
                            icon="oauth"
                          />
                          <Button
                            color={ComponentColor.Warning}
                            size={ComponentSize.Small}
                            shape={ButtonShape.Square}
                            text="Example"
                            icon="oauth"
                            disabled={true}
                          />
                        </td>
                        <td>
                          <Button
                            color={ComponentColor.Warning}
                            size={ComponentSize.Medium}
                            shape={ButtonShape.Square}
                            text="Example"
                            icon="oauth"
                          />
                          <Button
                            color={ComponentColor.Warning}
                            size={ComponentSize.Medium}
                            shape={ButtonShape.Square}
                            text="Example"
                            icon="oauth"
                            disabled={true}
                          />
                        </td>
                        <td>
                          <Button
                            color={ComponentColor.Warning}
                            size={ComponentSize.Large}
                            shape={ButtonShape.Square}
                            text="Example"
                            icon="oauth"
                          />
                          <Button
                            color={ComponentColor.Warning}
                            size={ComponentSize.Large}
                            shape={ButtonShape.Square}
                            text="Example"
                            icon="oauth"
                            disabled={true}
                          />
                        </td>
                      </tr>
                      <tr>
                        <td>Danger</td>
                        <td>
                          <Button
                            color={ComponentColor.Danger}
                            size={ComponentSize.ExtraSmall}
                            shape={ButtonShape.Square}
                            text="Example"
                            icon="oauth"
                          />
                          <Button
                            color={ComponentColor.Danger}
                            size={ComponentSize.ExtraSmall}
                            shape={ButtonShape.Square}
                            text="Example"
                            icon="oauth"
                            disabled={true}
                          />
                        </td>
                        <td>
                          <Button
                            color={ComponentColor.Danger}
                            size={ComponentSize.Small}
                            shape={ButtonShape.Square}
                            text="Example"
                            icon="oauth"
                          />
                          <Button
                            color={ComponentColor.Danger}
                            size={ComponentSize.Small}
                            shape={ButtonShape.Square}
                            text="Example"
                            icon="oauth"
                            disabled={true}
                          />
                        </td>
                        <td>
                          <Button
                            color={ComponentColor.Danger}
                            size={ComponentSize.Medium}
                            shape={ButtonShape.Square}
                            text="Example"
                            icon="oauth"
                          />
                          <Button
                            color={ComponentColor.Danger}
                            size={ComponentSize.Medium}
                            shape={ButtonShape.Square}
                            text="Example"
                            icon="oauth"
                            disabled={true}
                          />
                        </td>
                        <td>
                          <Button
                            color={ComponentColor.Danger}
                            size={ComponentSize.Large}
                            shape={ButtonShape.Square}
                            text="Example"
                            icon="oauth"
                          />
                          <Button
                            color={ComponentColor.Danger}
                            size={ComponentSize.Large}
                            shape={ButtonShape.Square}
                            text="Example"
                            icon="oauth"
                            disabled={true}
                          />
                        </td>
                      </tr>
                    </tbody>
                  </table>
                </div>
              </div>

              <div className="panel">
                <div className="panel-body">
                  <h3>Loading State Buttons</h3>
                  <table className="table">
                    <thead>
                      <tr>
                        <th />
                        <th>XS</th>
                        <th>SM</th>
                        <th>MD</th>
                        <th>LG</th>
                      </tr>
                    </thead>
                    <tbody>
                      <tr>
                        <td>Default</td>
                        <td>
                          <Button
                            color={ComponentColor.Default}
                            size={ComponentSize.ExtraSmall}
                            text="Example"
                            loading={true}
                            icon="oauth"
                          />
                          <Button
                            color={ComponentColor.Default}
                            size={ComponentSize.ExtraSmall}
                            text="Example"
                            loading={true}
                            icon="oauth"
                            disabled={true}
                          />
                        </td>
                        <td>
                          <Button
                            color={ComponentColor.Default}
                            size={ComponentSize.Small}
                            text="Example"
                            loading={true}
                            icon="oauth"
                          />
                          <Button
                            color={ComponentColor.Default}
                            size={ComponentSize.Small}
                            text="Example"
                            loading={true}
                            icon="oauth"
                            disabled={true}
                          />
                        </td>
                        <td>
                          <Button
                            color={ComponentColor.Default}
                            size={ComponentSize.Medium}
                            text="Example"
                            loading={true}
                            icon="oauth"
                          />
                          <Button
                            color={ComponentColor.Default}
                            size={ComponentSize.Medium}
                            text="Example"
                            loading={true}
                            icon="oauth"
                            disabled={true}
                          />
                        </td>
                        <td>
                          <Button
                            color={ComponentColor.Default}
                            size={ComponentSize.Large}
                            text="Example"
                            loading={true}
                            icon="oauth"
                          />
                          <Button
                            color={ComponentColor.Default}
                            size={ComponentSize.Large}
                            text="Example"
                            loading={true}
                            icon="oauth"
                            disabled={true}
                          />
                        </td>
                      </tr>
                      <tr>
                        <td>Primary</td>
                        <td>
                          <Button
                            color={ComponentColor.Primary}
                            size={ComponentSize.ExtraSmall}
                            text="Example"
                            loading={true}
                            icon="oauth"
                          />
                          <Button
                            color={ComponentColor.Primary}
                            size={ComponentSize.ExtraSmall}
                            text="Example"
                            loading={true}
                            icon="oauth"
                            disabled={true}
                          />
                        </td>
                        <td>
                          <Button
                            color={ComponentColor.Primary}
                            size={ComponentSize.Small}
                            text="Example"
                            loading={true}
                            icon="oauth"
                          />
                          <Button
                            color={ComponentColor.Primary}
                            size={ComponentSize.Small}
                            text="Example"
                            loading={true}
                            icon="oauth"
                            disabled={true}
                          />
                        </td>
                        <td>
                          <Button
                            color={ComponentColor.Primary}
                            size={ComponentSize.Medium}
                            text="Example"
                            loading={true}
                            icon="oauth"
                          />
                          <Button
                            color={ComponentColor.Primary}
                            size={ComponentSize.Medium}
                            text="Example"
                            loading={true}
                            icon="oauth"
                            disabled={true}
                          />
                        </td>
                        <td>
                          <Button
                            color={ComponentColor.Primary}
                            size={ComponentSize.Large}
                            text="Example"
                            loading={true}
                            icon="oauth"
                          />
                          <Button
                            color={ComponentColor.Primary}
                            size={ComponentSize.Large}
                            text="Example"
                            loading={true}
                            icon="oauth"
                            disabled={true}
                          />
                        </td>
                      </tr>
                      <tr>
                        <td>Secondary</td>
                        <td>
                          <Button
                            color={ComponentColor.Secondary}
                            size={ComponentSize.ExtraSmall}
                            text="Example"
                            loading={true}
                            icon="oauth"
                          />
                          <Button
                            color={ComponentColor.Secondary}
                            size={ComponentSize.ExtraSmall}
                            text="Example"
                            loading={true}
                            icon="oauth"
                            disabled={true}
                          />
                        </td>
                        <td>
                          <Button
                            color={ComponentColor.Secondary}
                            size={ComponentSize.Small}
                            text="Example"
                            loading={true}
                            icon="oauth"
                          />
                          <Button
                            color={ComponentColor.Secondary}
                            size={ComponentSize.Small}
                            text="Example"
                            loading={true}
                            icon="oauth"
                            disabled={true}
                          />
                        </td>
                        <td>
                          <Button
                            color={ComponentColor.Secondary}
                            size={ComponentSize.Medium}
                            text="Example"
                            loading={true}
                            icon="oauth"
                          />
                          <Button
                            color={ComponentColor.Secondary}
                            size={ComponentSize.Medium}
                            text="Example"
                            loading={true}
                            icon="oauth"
                            disabled={true}
                          />
                        </td>
                        <td>
                          <Button
                            color={ComponentColor.Secondary}
                            size={ComponentSize.Large}
                            text="Example"
                            loading={true}
                            icon="oauth"
                          />
                          <Button
                            color={ComponentColor.Secondary}
                            size={ComponentSize.Large}
                            text="Example"
                            loading={true}
                            icon="oauth"
                            disabled={true}
                          />
                        </td>
                      </tr>
                      <tr>
                        <td>Success</td>
                        <td>
                          <Button
                            color={ComponentColor.Success}
                            size={ComponentSize.ExtraSmall}
                            text="Example"
                            loading={true}
                            icon="oauth"
                          />
                          <Button
                            color={ComponentColor.Success}
                            size={ComponentSize.ExtraSmall}
                            text="Example"
                            loading={true}
                            icon="oauth"
                            disabled={true}
                          />
                        </td>
                        <td>
                          <Button
                            color={ComponentColor.Success}
                            size={ComponentSize.Small}
                            text="Example"
                            loading={true}
                            icon="oauth"
                          />
                          <Button
                            color={ComponentColor.Success}
                            size={ComponentSize.Small}
                            text="Example"
                            loading={true}
                            icon="oauth"
                            disabled={true}
                          />
                        </td>
                        <td>
                          <Button
                            color={ComponentColor.Success}
                            size={ComponentSize.Medium}
                            text="Example"
                            loading={true}
                            icon="oauth"
                          />
                          <Button
                            color={ComponentColor.Success}
                            size={ComponentSize.Medium}
                            text="Example"
                            loading={true}
                            icon="oauth"
                            disabled={true}
                          />
                        </td>
                        <td>
                          <Button
                            color={ComponentColor.Success}
                            size={ComponentSize.Large}
                            text="Example"
                            loading={true}
                            icon="oauth"
                          />
                          <Button
                            color={ComponentColor.Success}
                            size={ComponentSize.Large}
                            text="Example"
                            loading={true}
                            icon="oauth"
                            disabled={true}
                          />
                        </td>
                      </tr>
                      <tr>
                        <td>Warning</td>
                        <td>
                          <Button
                            color={ComponentColor.Warning}
                            size={ComponentSize.ExtraSmall}
                            text="Example"
                            loading={true}
                            icon="oauth"
                          />
                          <Button
                            color={ComponentColor.Warning}
                            size={ComponentSize.ExtraSmall}
                            text="Example"
                            loading={true}
                            icon="oauth"
                            disabled={true}
                          />
                        </td>
                        <td>
                          <Button
                            color={ComponentColor.Warning}
                            size={ComponentSize.Small}
                            text="Example"
                            loading={true}
                            icon="oauth"
                          />
                          <Button
                            color={ComponentColor.Warning}
                            size={ComponentSize.Small}
                            text="Example"
                            loading={true}
                            icon="oauth"
                            disabled={true}
                          />
                        </td>
                        <td>
                          <Button
                            color={ComponentColor.Warning}
                            size={ComponentSize.Medium}
                            text="Example"
                            loading={true}
                            icon="oauth"
                          />
                          <Button
                            color={ComponentColor.Warning}
                            size={ComponentSize.Medium}
                            text="Example"
                            loading={true}
                            icon="oauth"
                            disabled={true}
                          />
                        </td>
                        <td>
                          <Button
                            color={ComponentColor.Warning}
                            size={ComponentSize.Large}
                            text="Example"
                            loading={true}
                            icon="oauth"
                          />
                          <Button
                            color={ComponentColor.Warning}
                            size={ComponentSize.Large}
                            text="Example"
                            loading={true}
                            icon="oauth"
                            disabled={true}
                          />
                        </td>
                      </tr>
                      <tr>
                        <td>Danger</td>
                        <td>
                          <Button
                            color={ComponentColor.Danger}
                            size={ComponentSize.ExtraSmall}
                            text="Example"
                            loading={true}
                            icon="oauth"
                          />
                          <Button
                            color={ComponentColor.Danger}
                            size={ComponentSize.ExtraSmall}
                            text="Example"
                            loading={true}
                            icon="oauth"
                            disabled={true}
                          />
                        </td>
                        <td>
                          <Button
                            color={ComponentColor.Danger}
                            size={ComponentSize.Small}
                            text="Example"
                            loading={true}
                            icon="oauth"
                          />
                          <Button
                            color={ComponentColor.Danger}
                            size={ComponentSize.Small}
                            text="Example"
                            loading={true}
                            icon="oauth"
                            disabled={true}
                          />
                        </td>
                        <td>
                          <Button
                            color={ComponentColor.Danger}
                            size={ComponentSize.Medium}
                            text="Example"
                            loading={true}
                            icon="oauth"
                          />
                          <Button
                            color={ComponentColor.Danger}
                            size={ComponentSize.Medium}
                            text="Example"
                            loading={true}
                            icon="oauth"
                            disabled={true}
                          />
                        </td>
                        <td>
                          <Button
                            color={ComponentColor.Danger}
                            size={ComponentSize.Large}
                            text="Example"
                            loading={true}
                            icon="oauth"
                          />
                          <Button
                            color={ComponentColor.Danger}
                            size={ComponentSize.Large}
                            text="Example"
                            loading={true}
                            icon="oauth"
                            disabled={true}
                          />
                        </td>
                      </tr>
                    </tbody>
                  </table>
                </div>
              </div>
            </div>
          </div>
        </div>
      </FancyScrollbar>
    )
  }

  private get renderPanelHeading(): JSX.Element {
    const {onCreateDashboard} = this.props

    return (
      <>
        <div className="panel-heading">
          <h2 className="panel-title">{this.panelTitle}</h2>
          <div className="panel-controls">
            <SearchBar
              placeholder="Filter by Name..."
              onSearch={this.filterDashboards}
            />
            <Authorized requiredRole={EDITOR_ROLE}>
              <>
                <button
                  className="btn btn-sm btn-default"
                  onClick={this.handleToggleOverlay}
                >
                  <span className="icon import" /> Import Dashboard
                </button>
                <button
                  className="btn btn-sm btn-primary"
                  onClick={onCreateDashboard}
                >
                  <span className="icon plus" /> Create Dashboard
                </button>
              </>
            </Authorized>
          </div>
        </div>
        {this.renderImportOverlay}
      </>
    )
  }

  private get filteredDashboards(): Dashboard[] {
    const {dashboards} = this.props
    const {searchTerm} = this.state

    return dashboards.filter(d =>
      d.name.toLowerCase().includes(searchTerm.toLowerCase())
    )
  }

  private get panelTitle(): string {
    const {dashboards} = this.props

    if (dashboards === null) {
      return 'Loading Dashboards...'
    } else if (dashboards.length === 1) {
      return '1 Dashboard'
    }

    return `${dashboards.length} Dashboards`
  }

  private filterDashboards = (searchTerm: string): void => {
    this.setState({searchTerm})
  }

  private handleToggleOverlay = (): void => {
    this.setState({isOverlayVisible: !this.state.isOverlayVisible})
  }

  private get renderImportOverlay(): JSX.Element {
    const {onImportDashboard, notify} = this.props
    const {isOverlayVisible} = this.state

    return (
      <OverlayTechnology visible={isOverlayVisible}>
        <ImportDashboardOverlay
          onDismissOverlay={this.handleToggleOverlay}
          onImportDashboard={onImportDashboard}
          notify={notify}
        />
      </OverlayTechnology>
    )
  }
}

export default DashboardsPageContents
